import { LEVELS } from "../constants/levels";
const arrQuestioncsss = [
  {
    id: 1,
    title: "CSS là gì?",
    level: LEVELS.BASIC,
    summary: "CSS là ngôn ngữ dùng để style và layout cho HTML.",
    points: [
      "Viết tắt của `Cascading Style Sheets`.",
      "Dùng để chỉnh màu, kích thước, bố cục.",
    ],
    example: null,
  },
  {
    id: 2,
    title: "Cú pháp CSS như thế nào?",
    level: LEVELS.BASIC,
    summary: "CSS gồm selector và block khai báo.",
    points: ["Cú pháp: `selector { property: value; }`"],
    example: "p { color: red; }",
  },
  {
    id: 3,
    title: "Có mấy cách dùng CSS?",
    level: LEVELS.BASIC,
    summary: "Có 3 cách áp dụng CSS vào HTML.",
    points: [
      "`inline`: dùng `style` trong tag.",
      "`internal`: dùng `<style>` trong `<head>`.",
      "`external`: file `.css` riêng.",
    ],
    example: null,
  },
  {
    id: 4,
    title: "Selector là gì?",
    level: LEVELS.BASIC,
    summary: "Selector dùng để chọn phần tử cần style.",
    points: ["Ví dụ: `p`, `.class`, `#id`."],
    example: null,
  },
  {
    id: 5,
    title: "Class selector là gì?",
    level: LEVELS.BASIC,
    summary: "Chọn element theo class.",
    points: ["Dùng dấu `.`", "Có thể dùng cho nhiều element."],
    example: ".box { color: blue; }",
  },
  {
    id: 6,
    title: "ID selector là gì?",
    level: LEVELS.BASIC,
    summary: "Chọn element theo id.",
    points: ["Dùng dấu `#`.", "ID là duy nhất."],
    example: "#main { color: red; }",
  },
  {
    id: 7,
    title: "Độ ưu tiên CSS (specificity)?",
    level: LEVELS.INTERMEDIATE,
    summary: "Quy tắc quyết định style nào được áp dụng.",
    points: ["`inline` > `id` > `class` > `tag`."],
    example: null,
  },
  {
    id: 8,
    title: "`display` là gì?",
    level: LEVELS.BASIC,
    summary: "Quy định cách hiển thị của element.",
    points: ["Giá trị: `block`, `inline`, `inline-block`, `flex`, `none`."],
    example: null,
  },
  {
    id: 9,
    title: "`position` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Dùng để định vị element.",
    points: ["Giá trị: `static`, `relative`, `absolute`, `fixed`, `sticky`."],
    example: null,
  },
  {
    id: 10,
    title: "`flexbox` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Hệ thống layout một chiều (row hoặc column).",
    points: ["Dùng `display: flex`.", "Dễ căn giữa."],
    example: null,
  },
  {
    id: 11,
    title: "`justify-content` dùng làm gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Căn chỉnh theo trục chính.",
    points: ["Ví dụ: `center`, `space-between`."],
    example: null,
  },
  {
    id: 12,
    title: "`align-items` dùng làm gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Căn chỉnh theo trục phụ.",
    points: ["Ví dụ: `center`, `flex-start`."],
    example: null,
  },
  {
    id: 13,
    title: "`margin` là gì?",
    level: LEVELS.BASIC,
    summary: "Khoảng cách bên ngoài element.",
    points: ["Không có background."],
    example: null,
  },
  {
    id: 14,
    title: "`padding` là gì?",
    level: LEVELS.BASIC,
    summary: "Khoảng cách bên trong element.",
    points: ["Ảnh hưởng background."],
    example: null,
  },
  {
    id: 15,
    title: "`border` là gì?",
    level: LEVELS.BASIC,
    summary: "Viền của element.",
    points: ["Cú pháp: `border: 1px solid black;`"],
    example: null,
  },
  {
    id: 16,
    title: "`overflow` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Kiểm soát nội dung tràn ra ngoài.",
    points: ["`hidden`, `scroll`, `auto`."],
    example: null,
  },
  {
    id: 17,
    title: "`z-index` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Quy định thứ tự lớp hiển thị.",
    points: ["Số lớn hơn sẽ nằm trên."],
    example: null,
  },
  {
    id: 18,
    title: "`opacity` là gì?",
    level: LEVELS.BASIC,
    summary: "Độ trong suốt của element.",
    points: ["Giá trị từ `0` đến `1`."],
    example: null,
  },
  {
    id: 19,
    title: "`hover` là gì?",
    level: LEVELS.BASIC,
    summary: "Pseudo-class khi rê chuột vào element.",
    points: ["Viết dạng `:hover`."],
    example: "button:hover { color: red; }",
  },
  {
    id: 20,
    title: "`box-sizing` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Xác định cách tính kích thước box.",
    points: [
      "`content-box`: mặc định.",
      "`border-box`: tính cả padding + border.",
    ],
    example: null,
  },
  {
  id: 21,
  title: "CSS Grid là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Hệ thống layout 2 chiều.",
  points: [
    "Dùng `display: grid`.",
    "Có row và column.",
  ],
  example: null,
},
{
  id: 22,
  title: "BEM là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Quy tắc đặt tên class.",
  points: [
    "`block__element--modifier`.",
  ],
  example: null,
},
{
  id: 23,
  title: "Responsive design là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Thiết kế phù hợp nhiều màn hình.",
  points: [
    "Dùng `media queries`.",
  ],
  example: null,
},
{
  id: 24,
  title: "`will-change` là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Tối ưu performance animation.",
  points: [
    "Giúp browser chuẩn bị trước.",
  ],
  example: null,
},
{
  id: 25,
  title: "CSS variable là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Biến trong CSS.",
  points: [
    "Dùng `--name`.",
    "Truy cập bằng `var()`.",
  ],
  example: ":root { --main: red; }",
},
];
export default arrQuestioncsss;
