import { LEVELS } from "../constants/levels";

const arrQuestionHtmls = [
  {
    id: 1,
    title: "HTML là gì?",
    level: LEVELS.BASIC,
    summary: "HTML là ngôn ngữ đánh dấu dùng để xây dựng cấu trúc của website.",
    points: [
      "Viết tắt của `HyperText Markup Language`.",
      "Dùng để tạo layout cơ bản cho web.",
    ],
    example: null,
  },
  {
    id: 2,
    title: "HTML element là gì?",
    level: LEVELS.BASIC,
    summary: "Element là một phần tử HTML gồm thẻ mở, nội dung và thẻ đóng.",
    points: ["Cú pháp: `<tag>content</tag>`"],
    example: "<p>Hello</p>",
  },
  {
    id: 3,
    title: "HTML tag là gì?",
    level: LEVELS.BASIC,
    summary: "Tag là từ khóa được đặt trong dấu `<>` để xác định element.",
    points: ["Ví dụ: `<div>`, `<p>`, `<a>`"],
    example: null,
  },
  {
    id: 4,
    title: "Cấu trúc cơ bản của HTML?",
    level: LEVELS.BASIC,
    summary:
      "Một file HTML có cấu trúc chuẩn với `<!DOCTYPE html>`, `<html>`, `<head>`, `<body>`.",
    points: ["`<head>` chứa metadata.", "`<body>` chứa nội dung hiển thị."],
    example: null,
  },
  {
    id: 5,
    title: "Thẻ `<!DOCTYPE html>` là gì?",
    level: LEVELS.BASIC,
    summary: "Khai báo loại tài liệu HTML5 cho trình duyệt.",
    points: ["Luôn đặt ở dòng đầu tiên."],
    example: null,
  },
  {
    id: 6,
    title: "`<head>` dùng để làm gì?",
    level: LEVELS.BASIC,
    summary: "Chứa thông tin cấu hình cho trang web.",
    points: ["Ví dụ: `<title>`, `<meta>`, `<link>`."],
    example: null,
  },
  {
    id: 7,
    title: "`<body>` là gì?",
    level: LEVELS.BASIC,
    summary: "Chứa toàn bộ nội dung hiển thị trên trình duyệt.",
    points: ["Bao gồm text, hình ảnh, video..."],
    example: null,
  },
  {
    id: 8,
    title: "Thẻ `<a>` dùng để làm gì?",
    level: LEVELS.BASIC,
    summary: "Dùng để tạo liên kết (link).",
    points: ["Dùng attribute `href` để chỉ URL."],
    example: '<a href="https://example.com">Link</a>',
  },
  {
    id: 9,
    title: "Thẻ `<img>` là gì?",
    level: LEVELS.BASIC,
    summary: "Dùng để hiển thị hình ảnh.",
    points: ["Dùng `src` để chỉ đường dẫn.", "`alt` mô tả ảnh."],
    example: '<img src="image.jpg" alt="demo" />',
  },
  {
    id: 10,
    title: "Thẻ `<div>` là gì?",
    level: LEVELS.BASIC,
    summary: "Thẻ container dùng để nhóm các phần tử.",
    points: ["Là block element."],
    example: null,
  },
  {
    id: 11,
    title: "Thẻ `<span>` là gì?",
    level: LEVELS.BASIC,
    summary: "Dùng để nhóm nội dung inline.",
    points: ["Không xuống dòng."],
    example: null,
  },
  {
    id: 12,
    title: "Thẻ `<p>` là gì?",
    level: LEVELS.BASIC,
    summary: "Dùng để định nghĩa đoạn văn.",
    points: ["Tự động xuống dòng."],
    example: "<p>Paragraph</p>",
  },
  {
    id: 13,
    title: "Heading là gì?",
    level: LEVELS.BASIC,
    summary: "Các thẻ tiêu đề từ `<h1>` đến `<h6>`.",
    points: ["`<h1>` lớn nhất, `<h6>` nhỏ nhất."],
    example: "<h1>Title</h1>",
  },
  {
    id: 14,
    title: "Danh sách trong HTML?",
    level: LEVELS.BASIC,
    summary: "HTML có 2 loại danh sách chính.",
    points: [
      "`<ul>`: danh sách không thứ tự.",
      "`<ol>`: danh sách có thứ tự.",
      "`<li>`: phần tử.",
    ],
    example: null,
  },
  {
    id: 15,
    title: "Form trong HTML là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Dùng để thu thập dữ liệu từ người dùng.",
    points: ["Dùng `<form>`.", "Có input, button..."],
    example: null,
  },
  {
    id: 16,
    title: "Thẻ `<input>` là gì?",
    level: LEVELS.BASIC,
    summary: "Dùng để nhập dữ liệu.",
    points: ["Có nhiều type: `text`, `password`, `email`..."],
    example: '<input type="text" />',
  },
  {
    id: 17,
    title: "Thẻ `<button>` là gì?",
    level: LEVELS.BASIC,
    summary: "Tạo nút bấm.",
    points: ["Có thể dùng trong form."],
    example: "<button>Click</button>",
  },
  {
    id: 18,
    title: "Semantic HTML là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Sử dụng thẻ có ý nghĩa để cải thiện SEO và accessibility.",
    points: ["Ví dụ: `<header>`, `<footer>`, `<article>`."],
    example: null,
  },
  {
    id: 19,
    title: "Thẻ `<meta>` dùng để làm gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Cung cấp metadata cho trang web.",
    points: ["Ví dụ charset, viewport."],
    example: '<meta charset="UTF-8">',
  },
  {
    id: 20,
    title: "Thẻ `<link>` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Dùng để liên kết file bên ngoài.",
    points: ["Thường dùng để link CSS."],
    example: '<link rel="stylesheet" href="style.css">',
  },
  {
  id: 21,
  title: "SEO trong HTML là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Tối ưu HTML để cải thiện thứ hạng tìm kiếm.",
  points: [
    "Dùng semantic tags như `<article>`, `<section>`.",
    "Tối ưu `<meta>` và heading.",
  ],
  example: null,
},
{
  id: 22,
  title: "Accessibility (a11y) là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Làm website dễ dùng cho mọi người.",
  points: [
    "Dùng `alt`, `aria-*`.",
    "Hỗ trợ screen reader.",
  ],
  example: null,
},
{
  id: 23,
  title: "Lazy loading là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Chỉ load tài nguyên khi cần.",
  points: [
    "Tăng performance.",
  ],
  example: '<img loading="lazy" src="img.jpg" />',
},
{
  id: 24,
  title: "Data attribute là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Custom attribute lưu data trong HTML.",
  points: [
    "Cú pháp: `data-*`.",
  ],
  example: '<div data-id="1"></div>',
},
{
  id: 25,
  title: "Preload vs Prefetch?",
  level: LEVELS.ADVANCED,
  summary:
    "Tối ưu tải tài nguyên.",
  points: [
    "`preload`: load ngay.",
    "`prefetch`: load khi rảnh.",
  ],
  example: null,
},
];

export default arrQuestionHtmls;
