import { LEVELS } from "../constants/levels";
const arrQuestionjss = [
  {
    id: 1,
    title: "JavaScript là gì?",
    level: LEVELS.BASIC,
    summary:
      "JavaScript là ngôn ngữ lập trình dùng để tạo tương tác cho website.",
    points: ["Chạy trên trình duyệt.", "Có thể dùng cho backend (Node.js)."],
    example: null,
  },
  {
    id: 2,
    title: "Biến trong JS là gì?",
    level: LEVELS.BASIC,
    summary: "Biến dùng để lưu trữ dữ liệu.",
    points: ["Khai báo bằng `var`, `let`, `const`."],
    example: "let a = 10;",
  },
  {
    id: 3,
    title: "`var`, `let`, `const` khác nhau gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Khác nhau về phạm vi và khả năng thay đổi.",
    points: [
      "`var`: function scope.",
      "`let`: block scope.",
      "`const`: không gán lại.",
    ],
    example: null,
  },
  {
    id: 4,
    title: "Kiểu dữ liệu trong JS?",
    level: LEVELS.BASIC,
    summary: "JS có nhiều kiểu dữ liệu khác nhau.",
    points: [
      "`string`, `number`, `boolean`, `null`, `undefined`, `object`, `array`.",
    ],
    example: null,
  },
  {
    id: 5,
    title: "Function là gì?",
    level: LEVELS.BASIC,
    summary: "Function là khối code thực hiện một nhiệm vụ.",
    points: ["Khai báo bằng `function`."],
    example: "function sum(a, b) { return a + b; }",
  },
  {
    id: 6,
    title: "Arrow function là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Cách viết function ngắn gọn hơn.",
    points: ["Cú pháp: `() => {}`"],
    example: "const sum = (a, b) => a + b;",
  },
  {
    id: 7,
    title: "Array là gì?",
    level: LEVELS.BASIC,
    summary: "Array là danh sách các giá trị.",
    points: ["Dùng `[]`."],
    example: "let arr = [1, 2, 3];",
  },
  {
    id: 8,
    title: "Object là gì?",
    level: LEVELS.BASIC,
    summary: "Object lưu dữ liệu dạng key-value.",
    points: ["Dùng `{}`."],
    example: "let obj = { name: 'A' };",
  },
  {
    id: 9,
    title: "DOM là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "DOM là mô hình đối tượng của HTML.",
    points: ["Cho phép JS thao tác HTML."],
    example: null,
  },
  {
    id: 10,
    title: "`document.querySelector` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Dùng để chọn element trong DOM.",
    points: ["Trả về phần tử đầu tiên."],
    example: "document.querySelector('.box');",
  },
  {
    id: 11,
    title: "Event là gì?",
    level: LEVELS.BASIC,
    summary: "Event là hành động của người dùng.",
    points: ["Ví dụ: click, hover."],
    example: null,
  },
  {
    id: 12,
    title: "`addEventListener` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Gắn sự kiện cho element.",
    points: ["Cú pháp: `element.addEventListener()`."],
    example: "btn.addEventListener('click', fn);",
  },
  {
    id: 13,
    title: "Callback là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Function truyền vào function khác.",
    points: ["Dùng trong async."],
    example: null,
  },
  {
    id: 14,
    title: "Promise là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Đối tượng xử lý bất đồng bộ.",
    points: ["Có `then`, `catch`."],
    example: null,
  },
  {
    id: 15,
    title: "`async/await` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Cách viết async dễ đọc hơn.",
    points: ["Dùng với Promise."],
    example: null,
  },
  {
    id: 16,
    title: "`==` vs `===`?",
    level: LEVELS.INTERMEDIATE,
    summary: "So sánh lỏng và chặt.",
    points: ["`==`: ép kiểu.", "`===`: so sánh cả kiểu."],
    example: null,
  },
  {
    id: 17,
    title: "Loop trong JS?",
    level: LEVELS.BASIC,
    summary: "Dùng để lặp.",
    points: ["`for`, `while`, `forEach`."],
    example: null,
  },
  {
    id: 18,
    title: "`map()` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Duyệt array và trả về array mới.",
    points: ["Không thay đổi array gốc."],
    example: "arr.map(x => x * 2);",
  },
  {
    id: 19,
    title: "`filter()` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Lọc phần tử trong array.",
    points: ["Trả về array mới."],
    example: "arr.filter(x => x > 2);",
  },
  {
    id: 20,
    title: "`localStorage` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Lưu dữ liệu trên trình duyệt.",
    points: ["Không mất khi reload."],
    example: "localStorage.setItem('key', 'value');",
  },
  {
  id: 21,
  title: "Closure là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Function nhớ scope bên ngoài.",
  points: [
    "Dùng để encapsulation.",
  ],
  example: null,
},
{
  id: 22,
  title: "Hoisting là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "JS đưa khai báo lên đầu scope.",
  points: [
    "`var` bị hoisting.",
    "`let`, `const` không.",
  ],
  example: null,
},
{
  id: 23,
  title: "`this` trong JS là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Đại diện context hiện tại.",
  points: [
    "Phụ thuộc cách gọi function.",
  ],
  example: null,
},
{
  id: 24,
  title: "Prototype là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Cơ chế kế thừa trong JS.",
  points: [
    "Object có prototype chain.",
  ],
  example: null,
},
{
  id: 25,
  title: "Event loop là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Cơ chế xử lý async của JS.",
  points: [
    "Gồm call stack + queue.",
  ],
  example: null,
},
];
export default arrQuestionjss;
