import { LEVELS } from "../constants/levels";
const arrQuestionReacts = [
  {
    id: 1,
    title: "React là gì?",
    level: LEVELS.BASIC,
    summary: "React là thư viện JavaScript dùng để xây dựng UI.",
    points: ["Do `Facebook` phát triển.", "Dựa trên component."],
    example: null,
  },
  {
    id: 2,
    title: "Component là gì?",
    level: LEVELS.BASIC,
    summary: "Component là khối UI độc lập và có thể tái sử dụng.",
    points: ["Có thể là function hoặc class."],
    example: "function App() { return <h1>Hello</h1>; }",
  },
  {
    id: 3,
    title: "JSX là gì?",
    level: LEVELS.BASIC,
    summary: "JSX là cú pháp giống HTML trong JavaScript.",
    points: ["Dùng trong React để viết UI."],
    example: "const el = <h1>Hello</h1>;",
  },
  {
    id: 4,
    title: "Props là gì?",
    level: LEVELS.BASIC,
    summary: "Props dùng để truyền dữ liệu giữa các component.",
    points: ["Chỉ đọc (read-only)."],
    example: "<App name='A' />",
  },
  {
    id: 5,
    title: "State là gì?",
    level: LEVELS.BASIC,
    summary: "State là dữ liệu bên trong component.",
    points: ["Có thể thay đổi."],
    example: null,
  },
  {
    id: 6,
    title: "`useState` là gì?",
    level: LEVELS.BASIC,
    summary: "Hook dùng để quản lý state.",
    points: ["Cú pháp: `const [state, setState] = useState()`."],
    example: "const [count, setCount] = useState(0);",
  },
  {
    id: 7,
    title: "`useEffect` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Hook dùng để xử lý side effect.",
    points: ["Chạy sau khi render."],
    example: "useEffect(() => {}, []);",
  },
  {
    id: 8,
    title: "Virtual DOM là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Bản sao của DOM thật để tối ưu render.",
    points: ["Giúp React update nhanh hơn."],
    example: null,
  },
  {
    id: 9,
    title: "Event trong React?",
    level: LEVELS.BASIC,
    summary: "Xử lý sự kiện tương tự JS nhưng dùng camelCase.",
    points: ["Ví dụ: `onClick`, `onChange`."],
    example: "<button onClick={handleClick}>Click</button>",
  },
  {
    id: 10,
    title: "Conditional rendering là gì?",
    level: LEVELS.BASIC,
    summary: "Render UI dựa trên điều kiện.",
    points: ["Dùng `if`, `&&`, `? :`."],
    example: null,
  },
  {
    id: 11,
    title: "List và key trong React?",
    level: LEVELS.INTERMEDIATE,
    summary: "Render danh sách với key để tối ưu.",
    points: ["Key phải unique."],
    example: "items.map(i => <li key={i.id}>{i.name}</li>)",
  },
  {
    id: 12,
    title: "`useRef` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Hook dùng để truy cập DOM hoặc lưu giá trị.",
    points: ["Không gây re-render."],
    example: null,
  },
  {
    id: 13,
    title: "`useMemo` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Hook dùng để tối ưu tính toán.",
    points: ["Tránh tính lại không cần thiết."],
    example: null,
  },
  {
    id: 14,
    title: "`useCallback` là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Hook dùng để memo function.",
    points: ["Tránh tạo lại function."],
    example: null,
  },
  {
    id: 15,
    title: "Controlled component là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Form được điều khiển bởi state.",
    points: ["Dữ liệu nằm trong React."],
    example: null,
  },
  {
    id: 16,
    title: "Uncontrolled component là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Form dùng DOM để lưu dữ liệu.",
    points: ["Dùng `ref`."],
    example: null,
  },
  {
    id: 17,
    title: "React Router là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Thư viện dùng để điều hướng trong React.",
    points: ["SPA routing."],
    example: null,
  },
  {
    id: 18,
    title: "Lifting state up là gì?",
    level: LEVELS.INTERMEDIATE,
    summary: "Đưa state lên component cha để chia sẻ.",
    points: ["Giúp sync dữ liệu."],
    example: null,
  },
  {
    id: 19,
    title: "Fragment là gì?",
    level: LEVELS.BASIC,
    summary: "Nhóm nhiều element mà không tạo thêm DOM.",
    points: ["Dùng `<> </>`."],
    example: null,
  },
  {
    id: 20,
    title: "Hook là gì?",
    level: LEVELS.BASIC,
    summary: "Hook là function đặc biệt trong React.",
    points: ["Bắt đầu bằng `use`."],
    example: null,
  },
  {
  id: 21,
  title: "Context API là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Chia sẻ state toàn app.",
  points: [
    "Tránh prop drilling.",
  ],
  example: null,
},
{
  id: 22,
  title: "Redux là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "State management library.",
  points: [
    "Store, reducer, action.",
  ],
  example: null,
},
{
  id: 23,
  title: "Memoization trong React?",
  level: LEVELS.ADVANCED,
  summary:
    "Tối ưu render.",
  points: [
    "`React.memo`, `useMemo`.",
  ],
  example: null,
},
{
  id: 24,
  title: "Code splitting là gì?",
  level: LEVELS.ADVANCED,
  summary:
    "Chia nhỏ bundle để load nhanh.",
  points: [
    "Dùng `React.lazy`.",
  ],
  example: null,
},
{
  id: 25,
  title: "SSR vs CSR?",
  level: LEVELS.ADVANCED,
  summary:
    "So sánh render server và client.",
  points: [
    "`SSR`: nhanh SEO.",
    "`CSR`: nhanh tương tác.",
  ],
  example: null,
},
];
export default arrQuestionReacts;
